### ISSUE TITLE
Library won't compile - protected error

### ISSUE THREAD

**Issue by richwriroo** [disk91/Disk91_LoRaE5#2]
Hi - I am getting the following error when trying to compile (wio terminal) - Arduino IDE or PIO.  I am following the instructions here: https://wiki.seeedstudio.com/Connecting-to-TTN/

Arduino: 1.8.19 (Windows 10), Board: "Seeeduino Wio Terminal, Master, Enabled, 120 MHz (standard), Small (-Os) (standard), 50 MHz (standard), Arduino, Off, On"

lorae5.sendATCommand("AT+ID=AppEUI","","+ID: ERROR","",1000,false,NULL);

\Arduino\libraries\Disk91_LoRaE5-master\src/disk91_LoRaE5.h:139:10: note: declared protected here

bool sendATCommand(                     // Send an AT command to the E5 module

'bool Disk91_LoRaE5::sendATCommand(const char*, const char*, const char*, const char*, uint32_t, bool, bool (*)(Disk91_LoRaE5*))' is protected within this context

**Comment by disk91** [comment]
yes, better to add the feature you need in the library and propose a pull request if making sense to others. I don't want to underlaying to be public so I can modify it, improve it w/o impacting the public API and ensure the compatibility of existing code with future versions
