### ISSUE TITLE
Panic on ESP32

### ISSUE THREAD

**Issue by baldvinhansson** [disk91/Disk91_LoRaE5#4]
Can you imagine what would make this library cause "Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled." when run on an ESP32?

I'm just initializing for EU868 and all goes well until the call to join_sync() - in my case the chip can not join the network (no gateways in range) and it will write out

-> LoRaE5 - recv +JOIN: Join failed
-> LoRaE5 - AT ending with error
-> LoRaE5 - recv +JOIN: Done

then return from the call and immediately the Guru Meditation Error occurs.

I'm stumped. Hope someone might have got this to work on ESP32 and I'm just missing some minor details. Any help is greatly appreciated!

**Comment by disk91** [comment]
Hello,
Can you give more details please ?
What serial is used on esp32 for the e5 board ?

do you have any other code than just the simple uplink exemple ?

**Comment by baldvinhansson** [comment]
I'm using Serial for debug and HardwareSerial for communicating with the LoRa E5. For example, this code, adopted from one of the examples of the library, will crash as soon as I run it on the ESP32.
```
#include <Arduino.h>
#include "disk91_LoRaE5.h"

HardwareSerial serialLoRa(2); // 2=UART3

Disk91_LoRaE5 lorae5(&Serial); // Where the AT command and debut traces are printed

uint8_t deveui[] = { 0xDC, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0xEE };
uint8_t appeui[] = { 0x2C, 0xF7, 0xF1, 0x20, 0x42, 0x00, 0x84, 0x0A };
uint8_t appkey[] = { 0x2A, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0xA1, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0x43 };

void setup() {
   Serial.begin(9600);
   uint32_t start = millis();
   while ( !Serial && (millis() - start) < 1500 );  // Open the Serial Monitor to get started or wait for 1.5"

   serialLoRa.begin(9600, SERIAL_8N1, 14, 13); // RX (LoRa > ESP32), TX (ESP32 > LoRa)
   
   // init the library, search the LORAE5 over the different WIO port available
   if ( ! lorae5.begin(DSKLORAE5_HWSERIAL_CUSTOM, &serialLoRa) ) {
      Serial.println("LoRa E5 Init Failed");
      while(1); 
   }

   // Setup the LoRaWan Credentials
   if ( ! lorae5.setup(
         DSKLORAE5_ZONE_EU868,     // LoRaWan Radio Zone EU868 here
         deveui,
         appeui,
         appkey
      ) ){
      Serial.println("LoRa E5 Setup Failed");
      while(1);         
   }
}

void loop() {
   static uint8_t data[] = { 0x01, 0x02, 0x03, 0x04 }; 

   if ( lorae5.send_sync(
         1,              // LoRaWan Port
         data,           // data array
         sizeof(data),   // size of the data
         false,          // we are not expecting a ack
         7,              // Spread Factor
         14              // Tx Power in dBm
      ) 
   ) {
      Serial.println("Uplink done");
      if ( lorae5.isDownlinkReceived() ) {
         Serial.println("A downlink has been received");
         if ( lorae5.isDownlinkPending() ) {
         Serial.println("More downlink are pending");
         }
      }
   }

   delay(30000);
}
```

Results in:
...
09:40:18.388 -> LoRaE5 - recv +JOIN: Join failed
09:40:18.388 -> LoRaE5 - AT ending with error
09:40:18.388 -> LoRaE5 - recv +JOIN: Done
09:40:18.388 -> Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
09:40:18.388 -> Memory dump at 0x400d35dc: bba502ad 000000ff 20006136
09:40:18.388 -> Core  1 register dump:
09:40:18.388 -> PC      : 0x400d35e1  PS      : 0x00060a30  A0      : 0x800d23e8  A1      : 0x3ffcaa90  
09:40:18.388 -> A2      : 0x3ffbc210  A3      : 0x00000009  A4      : 0x0000000e  A5      : 0x3ffbdb78  
09:40:18.388 -> A6      : 0x3ffbdb68  A7      : 0x3ffbc210  A8      : 0x800d35e1  A9      : 0x3ffca9a0  
09:40:18.422 -> A10     : 0x00000000  A11     : 0xdbdfa107  A12     : 0xdbdfa107  A13     : 0x00000001  
09:40:18.422 -> A14     : 0x00000000  A15     : 0x3ffbc310  SAR     : 0x0000000a  EXCCAUSE: 0x00000000  
09:40:18.422 -> EXCVADDR: 0x00000000  LBEG    : 0x40090769  LEND    : 0x40090779  LCOUNT  : 0xfffffffd  
09:40:18.422 -> 
09:40:18.422 -> 
09:40:18.422 -> Backtrace:0x400d35de:0x3ffcaa900x400d23e5:0x3ffcaad0 0x400d5426:0x3ffcab00

**Comment by baldvinhansson** [comment]
For future reference, and in case it helps anyone. I believe I figured out the problem.

sendReceive_sync() and send_sync() and join_sync() are supposed to return bool and do not return anything. This messes up the stack and panics the ESP32. Fixing these will at the very least prevent that particular problem. I will be testing the library further, now that it's up and running on the ESP32 and should I find further issues, I'll raise issues to clarify.

Thank you again for your work on this library. It will obviously save me a ton of work to be able to use this rather than write it from scratch.

**Comment by disk91** [comment]
Thank you for reporting, this is fixed now
